all: conll-rdf

conll-rdf:
	# clone CoNLL-RDF
	# NOTE: to avoid having multiple copies, create conll-rdf as a symlink to an
	#       existing installation before calling make
	git clone https://github.com/acoli-repo/conll-rdf
